apiVersion: v2
appVersion: '1.0'
description: A Helm chart for labs-beardfacekainos-nodejs App
name: labs-beardfacekainos-nodejs
home: https://github.com/hmcts/labs-beardfacekainos-nodejs
version: 0.0.8
dependencies:
  - name: nodejs
    version: 3.2.0
    repository: 'oci://hmctssbox.azurecr.io/helm'
